#!/bin/bash

echo "📋 LECHWORLD SETUP CHECKLIST"
echo "============================"
echo ""
echo "[ ] 1. Create Supabase account (https://supabase.com)"
echo "[ ] 2. Create new project 'lechworld'"
echo "[ ] 3. Choose strong database password"
echo "[ ] 4. Select São Paulo region"
echo "[ ] 5. Wait for project to initialize"
echo "[ ] 6. Get credentials from Settings → API"
echo "[ ] 7. Run: ./setup-new-supabase.sh"
echo "[ ] 8. Follow all prompts"
echo "[ ] 9. Test at https://lechworld.fly.dev"
echo "[ ] 10. Change default password!"
echo ""
echo "Total time: ~15 minutes"
echo ""
echo "Ready? Start at: https://supabase.com"