#!/bin/bash

echo "🚂 Railway GitHub Deployment Setup"
echo "=================================="
echo ""
echo "Since Railway CLI requires interactive terminal for linking,"
echo "here's how to deploy via GitHub integration:"
echo ""
echo "📱 OPTION 1: Railway Dashboard (Recommended)"
echo "----------------------------------------"
echo "1. Open: https://railway.app/dashboard"
echo "2. Click on 'lechworld-api' project"
echo "3. Go to Settings → GitHub"
echo "4. Connect to repo: leolech14/lechworld"
echo "5. Set branch: main"
echo "6. Set root directory: / (since railway.toml handles paths)"
echo "7. Railway will auto-deploy your latest commit:"
echo "   - Commit: 'fix: Railway deployment configuration for npm workspaces monorepo'"
echo ""
echo "📝 OPTION 2: Terminal (if you have terminal access)"
echo "---------------------------------------------------"
echo "cd /Users/lech/Projects-A/PROJECT_lechworld"
echo "railway link"
echo "# Select: lechworld-api"
echo "railway up"
echo ""
echo "🔍 OPTION 3: Check deployment status"
echo "------------------------------------"
echo "Your latest commit is already pushed to GitHub."
echo "If Railway is connected, it should be deploying now."
echo ""
echo "Visit: https://railway.app/project/lechworld-api"
echo ""
echo "📊 Expected behavior after deployment:"
echo "--------------------------------------"
echo "✅ Build command: npm install && npm run build:api"
echo "✅ Start command: npm run start:api"
echo "✅ Health check: GET /health"
echo "✅ Port: Provided by Railway (PORT env var)"
echo ""
echo "🐛 If deployment fails, check:"
echo "------------------------------"
echo "1. Railway logs for build errors"
echo "2. Ensure NODE_ENV is set to 'production'"
echo "3. Check if all dependencies are in package.json"
echo "4. Verify the health endpoint responds within 30s"